using System;
using System.Collections.Generic;
using System.Net;
using System.Net.Sockets;
using System.Text;





//there are actually two namespaces in this .cs (VATestPlugin, VATestWinampPlugin... see way down below) and each contain a class that would be considered a, 'plugin' (since each contain the necessary static functions to be a VoiceAttack plugin)

namespace VoiceAttackFO4Plugin
{

    public class VoiceAttackPlugin
    {

        

        public static string VA_DisplayName()
        {
            return "Voice Attack FO4Plugin";  //this is what you will want displayed in dropdowns as well as in the log file to indicate the name of your plugin
        }

        public static string VA_DisplayInfo()
        {
            return "VoiceAttackPlugin\r\n\r\nTo be used with Fallout 4\r\n\r\n2014 VoiceAttack";  //this is just extended info that you might want to give to the user.  note that you should format this up properly.
        } 

        public static Guid VA_Id()
        {
            
            return new Guid("{77679D45-2745-44B8-8777-D35E600E5B6E}");  //this id must be generated by YOU... it must be unique so VoiceAttack can identify and use the plugin
        }

        public static void VA_Init1(ref Dictionary<string, object> state, ref Dictionary<string, Int16?> conditions, ref Dictionary<string, string> textValues, ref Dictionary<string, object> extendedValues)
        {
            //this is where you can set up whatever session information that you want.  this will only be called once on voiceattack load, and it is called asynchronously.
            //the state parameter is a local copy of the state held on to by VoiceAttack.  In this case, the state will be a dictionary with zero items.  You can add as many items to hold on to as you want.
            //the conditions and textValues will also be empty.  You can add whatever you want to those lists and VoiceAttack will copy the values into its own lists

            conditions.Add("initializedCondition1", 1);  //add some meaningless example conditions
            conditions.Add("initializedCondition2", 2);

            textValues.Add("initializedText1", "This is 1");  //add some meaningless example text values
            textValues.Add("initializedText2", "This is 2");

            state.Add("new state value", 369);  //add whatever private state information you want to maintain
            state.Add("second new state value", "hello");
        }

        public static void VA_Exit1(ref Dictionary<string, object> state)
        {
            //this function gets called when VoiceAttack is closing (normally).  You would put your cleanup code in here, but be aware that your code must be robust enough to not absolutely depend on this function being called
            if (state.ContainsKey("myStateValue"))
            {
                //do some kind of file cleanup or whatever at this point
            }
        }

        public static void VA_Invoke1(String context, ref Dictionary<string, object> state, ref Dictionary<string, Int16?> conditions, ref Dictionary<string, string> textValues, ref Dictionary<string, object> extendedValues)
        {
            
            string strVariable = "";
            string strCommand = "";
            string strMsg = "";
            textValues["ReturnMessage"] = "Strart";
            if (textValues.ContainsKey("Home_Location")) //was the text value passed in?
            {
                if (textValues["Home_Location"] == null) //if the value is null, set the value to, 'Vault 111'
                {
                    strVariable = "Vault 111";
                }

                else
                {
                    strVariable = textValues["Home_Location"];
                }

                    
            }

            if (textValues.ContainsKey("FT_Location")) //was the text value passed in?
            {
                if (textValues["FT_Location"] == null) //if the value is null, set the value to, 'Vault 111'
                {
                    strVariable = "Vault 111";
                }

                else
                {
                    strVariable = textValues["FT_Location"];
                   
                }

            }
            if (textValues.ContainsKey("SentCommand"))
            {
                if (textValues["SentCommand"] == null)
                {
                    textValues["ReturnMessage"] = "No Command Was given";
                    
                    return;
                }
                else
                {
                    strCommand = textValues["SentCommand"];
                    textValues["ReturnMessage"] = "Command Sent";
                }
                    
            }

            if (textValues.ContainsKey("Direction_Location")) 
            {
                if (textValues["Direction_Location"] == null) //if the value is null, set the value to, 'Vault 111'
                {
                    strVariable = "Vault 111";
                }

                else
                {
                    strVariable = textValues["Direction_Location"];

                }

            }


           
            strMsg = strCommand + ";" + strVariable;
            String sndClient = SendMsg(IPAddress.Parse("127.0.0.1"), 8089, strMsg);
            textValues["ServerResponse"] = sndClient;
        }


        static public string SendMsg(IPAddress ipAddress, int thePort, string themessage)
        {
            byte[] bytes = new byte[1024];
            string result = "";
            // Connect to a remote device.
            try
            {
                // Establish the remote endpoint for the socket.
                // This example uses port 11000 on the local computer.
                IPHostEntry ipHostInfo = Dns.GetHostEntry(Dns.GetHostName());
                IPEndPoint remoteEP = new IPEndPoint(ipAddress, thePort);

                // Create a TCP/IP  socket.
                Socket sender = new Socket(ipAddress.AddressFamily, SocketType.Stream, ProtocolType.Tcp);

                // Connect the socket to the remote endpoint. Catch any errors.
                try
                {
                    sender.Connect(remoteEP);


                    // Encode the data string into a byte array.
                    byte[] msg = Encoding.ASCII.GetBytes(themessage);

                    // Send the data through the socket.
                    int bytesSent = sender.Send(msg);

                    // Receive the response from the remote device.
                    int bytesRec = sender.Receive(bytes);
                    result = String.Format("{0}", Encoding.ASCII.GetString(bytes, 0, bytesRec));
                    return result;
                    // Release the socket.
                    sender.Shutdown(SocketShutdown.Both);
                    sender.Close();

                }
                catch (ArgumentNullException ane)
                {
                    Console.WriteLine("ArgumentNullException : {0}", ane.ToString());
                    result = "Erro1";
                    return result;
                }
                catch (SocketException se)
                {
                    Console.WriteLine("SocketException : {0}", se.ToString());
                    result = "Not Connected";
                    return result;
                }
                catch (Exception e)
                {
                    Console.WriteLine("Unexpected exception : {0}", e.ToString());
                    result = "Erro3";
                    return result;
                }

            }
            catch (Exception e)
            {
                Console.WriteLine(e.ToString());
                result = "Erro4";
                return result;
            }

        }



    }

}




